config/routes.rb
Creators::Application.routes.draw do
  
  resources :admin, only: [:index]
  resources :posts do
    member do
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
  end

  match "/posts/add_new_comment" => "staticpage#add_new_comment", :as => "add_new_comment_to_posts", :via => [:post]
  get '/my_posts', to: 'staticpage#my_posts', as: 'my_posts'
  get '/my_posts/:id/preview', to: 'staticpage#preview', as: 'preview'
  get '/show/:id', to: 'staticpage#show', as: 'show_staticpage'
  get '/user/:id', to: 'admin#user', as: 'show_user'
  get 'admin/:id/publish_unpublish_post', to: 'admin#publish_unpublish_post', as: 'public'
  get 'admin/post/:id/comments',  to: 'admin#posts_comments', as: 'comments'
  delete '/comment/:id', :to => 'admin#destroy', as: 'delete_comments'
  get "/:category" => 'staticpage#home', as: :home_category
  get 'user/perfil/:id',  to: 'staticpage#perfil_usuario', as: 'perfil'
  post "staticpage/enviar_contacto", path: "enviarContacto"

  devise_for :users

  root 'staticpage#home'

end

app/controllers/staticpage_controller.rb
class StaticpageController < ApplicationController
  def home
    if params[:search]
      @posts = Post.search(params[:search])
      if @posts.class == Array
        @posts = Kaminari.paginate_array(@posts).page(params[:page]).per(6) 
      else
        @posts = @posts.page(params[:page]).per(6)
      end
    elsif params[:category]
      @posts = params[:category] == "0" ? Post.where("category_id != ? AND public = ?", "3", true).page(params[:page]) : Post.where("category_id = ? AND public = ?", params[:category], true).page(params[:page])
    else 
      @posts = Post.where("category_id != ? AND public = ?", "3", true).page(params[:page])
    end
  end

  def my_posts
    @posts = Post.where(user_id: current_user.id)
  end

  def preview
  	@post = Post.find(params[:id])
  end

  def show
  	@post = Post.find(params[:id])
  end

  def add_new_comment
    post = Post.find(params[:id])
    post.comments << Comment.new(comment: params[:comment], user_id: params[:user_id], name: params[:name])
    redirect_to show_staticpage_path(post.id, anchor: 'comment-area')
  end

  def posts_category
    @posts = params[:category] == "0" ? Post.where("category_id != ? AND public = ?", "4", true).page(params[:page]) : Post.where("category_id = ? AND public = ?", params[:category], true).page(params[:page])
  end

  def perfil_usuario
    @posts = Post.where(user_id: params[:id]).page(params[:page])
    @usuario = User.find(params[:id])
  end

  def enviar_contacto
    #if simple_captcha_valid?
      ContactMailer.contact(params).deliver
      redirect_to root_path, notice: params[:name]+', ¡Tu mensaje ha sido en enviado!'
    #else
      #redirect_to root_path(anchor: "contactanos"), alert: 'Error al ingresar el captcha, vuelva a intentar'
    #end
  end
end

app/helpers/staticpage_helper.rb
module StaticpageHelper
end

app/views/staticpage/_posts.html.haml
#categories
	.container
		%center 
			.title-section
				%b
					CATEGORÍAS
			.subtitle-section
				Conóce las publicaciones de los creadores
			.line-section{ style: "margin-bottom: 18px;"}
			.col-lg-4.col-md-4.col-sm-4.col-xs-12.col-lg-offset-8.col-md-offset-8.col-sm-offset-8
				= form_tag root_path(anchor: "all-post"), :method => 'get', class: "pull-right"do
					.input-group
						= text_field_tag :search, params[:search], class: "form-control"
						%span.input-group-btn
							= submit_tag "Search", :name => nil, class: "form-control"
			%br
			%br/ 
			%ul.nav.nav-pills.center-pills
				%li{ class: "#{'active' if params[:category] == 0.to_s}"}
					=link_to "Todas", home_category_path(0, anchor: "categories")
				%li{ class: "#{'active' if params[:category] == 1.to_s}"}
					=link_to "Narrativa", home_category_path(1, anchor: "categories")
				%li{ class: "#{'active' if params[:category] == 2.to_s}"}
					=link_to "Poesia", home_category_path(2, anchor: "categories")
				%li{ class: "#{'active' if params[:category] == 3.to_s}"}
					=link_to "Audiovisual", home_category_path(3, anchor: "categories")
				/%li{ class: "#{'active' if params[:category] == 4.to_s}"}
				/=link_to "Audiovisual", home_category_path(4, anchor: "categories")
		.row#all-post{ style: "padding-top: 20px;" }
			- @posts.reverse.each_with_index do |p, index|
				- if index.modulo(3) == 0
					.row
				- if p.public
					.col-lg-4.col-md-4.col-sm-4.col-xs-12
						%center
							.type-img
								- if p.category_id == 1
									- case Random.rand(1..4)
										- when 1
											.type-img-narrativa-1
										- when 2
											.type-img-narrativa-2
										- when 3
											.type-img-narrativa-3
										- when 4
											.type-img-narrativa-4
								- elsif p.category_id == 2
									- case Random.rand(1..4)
										- when 1
											.type-img-poesia-1
										- when 2
											.type-img-poesia-2
										- when 3
											.type-img-poesia-3
										- when 4
											.type-img-poesia-4
								- elsif p.category_id == 3
									- case Random.rand(1..4)
										- when 1
											.type-img-audiovisual-1
										- when 2
											.type-img-audiovisual-2
										- when 3
											.type-img-audiovisual-3
										- when 4
											.type-img-audiovisual-4
								.cover
								%span#item.fa-stack.fa-lg{style:"font-size:50px;"} 
									%i.fa.fa-circle.fa-stack-2x{style:"color: white;"}
									%i.fa.fa-eye.fa-stack-1x{style: "color: #00A2FF;"}
								.flat-categories
									- if p.category_id == 1
										%i.fa.fa-comment.fa-3x{style: "color:#EFF2FB;"}
									- elsif p.category_id == 2
										%i.fa.fa-pencil.fa-3x{style: "color:#EFF2FB;"}
									- elsif p.category_id == 3
										%i.fa.fa-youtube-play.fa-3x{style: "color:#EFF2FB;"}
								.flat-dos.arrow-left
								.flat-tres.arrow-right
								= link_to show_staticpage_path(p.id), id: "item" do
									%span.fa-stack.fa-lg{style:"font-size:50px;"} 
										%i.fa.fa-circle.fa-stack-2x{style:"color: white;"}
										%i.fa.fa-eye.fa-stack-1x{style: "color: #00A2FF;"}
						%h4
							= p.title
						.autor
							%small
								= link_to "#{p.user.name}, ", perfil_path(p.user.id)
								= p.created_at.strftime("%B %d, %Y")
						- if p.category_id != 3
							%p{align:"justify", style:"color:#777;"}
								= "#{p.content.split(" ")[0..40].join(" ")}...".html_safe
						= link_to "Leer más", show_staticpage_path(p.id), class: "leer-mas pull-right", style: "margin-bottom: 15px;"
						%br/
		.row#paginate
			%center 
				= paginate @posts, params: { anchor: "all-post"}

:javascript
	function get_category_post(category) {
		$('#all-post').remove()		
		$('.pagination').remove()
		$.get("/"+category)
	}

	$('ul.nav-pills li a').click(function (e) {
	  $('ul.nav-pills li.active').removeClass('active')
	  $(this).parent('li').addClass('active')
	})

app/views/staticpage/home.html.haml
#home{style:"margin-top:-20px;"}
	- if flash[:notice]
		.container{ style: "background-color=#00A2FF:"}
			%center	
				.alert.alert-success#notice 
					%button{ type:"button", class: "close", "data-dismiss"=>"alert", "aria-hidden"=>"true"}
						%i.fa.fa-times
					%center
						= "#{flash[:notice]}"
	.item-principal-phone.visible-xs
		%center
			= image_tag "logo-white.png", :width => "300px"
	#myCarousel.carousel.slide.hidden-xs
		.carousel-inner
			.active.item.item-principal#item1
				= image_tag "portada.png"
	.container-register
		.container
			%center
				.text-register
					Forma Parte de esta Grandiosa Experiencia.
					%br.hidden-lg
					- unless current_user
						%a.btn.btn-primary.btn-login#registerButton{href:"/users/sign_up"}
							¡Regístrate Ahora!	
					%a.btn.btn-primary.btn-mensaje#registerButton{href:"#mensaje", "data-toggle"=>"modal", "data-target"=>"#mensaje"}
						¡Mensaje de Invitación!	

= render template: "layouts/nosotros"
= render template: "layouts/evento"
= render template: "layouts/patrocinantes"
= render 'posts'
= render template: "layouts/contactanos"
= render template: "staticpage/mensaje_invitacion"
:javascript 

	onepage();

app/views/staticpage/mensaje_invitacion.html.haml
#mensaje.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} ×
        %h4#myModalLabel.modal-title 
          %center
            %b 
              Mensaje de Invitación al Evento
      .modal-body{style:"font-family: 'Open Sans', 'sans-serif';"} 
        %center
          %h2
            3er Encuentro Literario de Jóvenes Creadores
        %br
        %p
          Vamos por el tercero
        %p  
          A mi pana M.V
        %p{align:"justify"}  
          Y a todos los seguidores de Santo Tomás de Aquino “ahorita estás fiebrúo, pero te vas a graduar, vas a empezar a trabajar y te vas a dar cuenta de que es muy difícil y cansón”… Sonaba a ritmo de balbuceo disfrazado de grito, empañado por alguna canción de fondo de una de esas pésimas bandas de “rock” que suelen colocar en La Mega. Yo miraba el rostro que escupía aquel epitafio mientras acariciaba una húmeda botella color ámbar, en mi lengua un festín amargo y dulce me invitaba a escuchar mi propia voz, a sonreír en silencio por lo que estaba por comenzar: eso en lo que muy pocos creían (es que es definitivo: Santo Tomás de Aquino tiene más seguidores que Messi, El Che, e incluso el mismísimo Ronald McDonald).
        %p{align:"justify"} 
          Han transcurrido ya dos años desde aquella noche previa a los preparativos del 
          %b 1er Encuentro Literario de Jóvenes Creadores
          , ya estamos en el tercero y no saben cuantas veces he fantaseado con que voy de copiloto en el DeLorean y le digo a Marty que me lleve ante aquel pana, solo para verlo atragantarse. Mentiría si les digo que no es agotador, si les negase que en cada encuentro se va quedando un pedazo de mí, irrecuperable, una porción de lo que era para ir mutando a lo que soy, una constante evolución a partir de lo que se sacrifica. Pero como muy bien dice la letra de aquella canción de Ilegales (Favor no confundir a la legendaria banda española con una cosa latina que existió hace algo más que una década) “Libérate aunque algo tenga que morir”.
        %p{align:"justify"} 
          Estamos ya encontrándonos por tercera vez consecutiva, entre nosotros, y a nosotros mismos, contagiándonos del delirio de hacer lo que nos gusta y como nos gusta.
        %p{align:"justify"} 
          Habrá rostros nuevos, otros no tanto, y tal vez la situación actual del país influya (para bien o para mal) pero en medio de tanta turbulencia política, económica y social, existimos un grupo de personas que sí quiere hacer algo, que repudia a la asquerosa tradición del “reposero” que pasa más días “de permiso” que trabajando, que le agarra una nalga a la apatía y después le invita una cerveza, personas que nos sentimos orgullosos de ignorar todo le lío de los dólares porque el mejor libro del mundo no tiene las páginas color verde. Le armamos una guerrilla de frente a los que no pueden creer sin ver. La Fundación
          %b MACHETE 
          como principal impulsor de esta empresa, junto a la Cátedra Libre de Literatura Agustín García, y demás colaboradores de toda esta realidad mancomunada, le enviamos (al más puro estilo de Rafael Alberti) un Burro Explosivo a todos esos panas que no creyeron en aquel sueño que ya ES: 
          %b EL TERCER ENCUENTRO LITERARIO DE JÓVENES CREADORES.
        %br
        %p{align:"center"}
          %span{style:"font-size:30px;"} 
            Luis Ramones  
          %br
          Fundador del 1er Encuentro Literario de Jóvenes Creadores.
          %br
          Presidente de la Fundación MACHETE
      .modal-footer{style:"margin-top: 0px;"}
        %button.btn.btn-primary{"data-dismiss" => "modal", type: "button"} Cerrar

app/views/staticpage/modalCrono.haml
#modalCrono.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} ×
        %h4#myModalLabel.modal-title 
          %center
            %b 
              CRONOGRAMA DEL EVENTO
      .modal-body        
        %table.table.table-bordered
          %tr
            %th.hidden-xs
              %center
                
            %th 
              %center
                Miércoles 18
            %th 
              %center
                Jueves 19
            %th 
              %center
                Viernes 20
          %tr
            %th.hidden-xs 
              %center
                Mañana
            %td 
              %center
                Recepción y entrega de materiales.
            %td 
              %center
                Recital de narrativa (presentado en el anfiteatro de módulo c).
            %td 
              %center
                Videoconferencia con autor internacional. 
                %br
                %br/ 
                Conversatorio sobre rock, música electrónica y hip hop. (en módulo c).
          %tr
            %th.hidden-xs 
              %center
                Tarde
            %td 
              %center
                Apertura y exposición de cronograma: Luis Ramones .
                %br
                %br/
                Palabras de Lic. Maylén.
                %br
                %br/
                Actividad Organizada por CELYL.
                %br
                %br/
                Intervención de Grupo Febrero.(anfiteatro de módulo c).
            %td 
              %center
                %br/ 
                %br/
                %br/ 
                %br/  
                Almuerzos.
                %br
                %br/
                Ida a
                %b 
                  MIACHICHE. 
                %br
                %br/
                Refrigerios.
            %td 
              %center
                %br/ 
                %br/ 
                %br/ 
                %br/ 
                Almuerzos.
                %br
                %br/
                Ida a
                %b 
                  ADÍCORA. 
                %br
                %br/
                Refrigerios.
          %tr
            %th.hidden-xs 
              %center
                Noche
            %td 
              %center
                Muestra fotográfica en Salón Santa Rosa (INCUDEF).
                %br/ 
                %br/ 
                Recital de poesía en el mismo INCUDEF.
                %br/ 
                %br/ 
                Noche de trova en Bar Garúa.
            %td 
              %center
                Presentación de obra de teatro (Club Bolívar).
                %br/ 
                %br/ 
                Exposición de audiovisuales.
            %td 
              %center
                Entrega de reconocimientos y clausura.
              %br/ 
              %br/ 
              Toque de bandas:
              %br/
              %b
                REVOLUCIÓN
              %br/ 
              %b
                MASMEGAHERTZ
      .modal-footer{style:"margin-top: 0px;"}
        %button.btn.btn-primary{"data-dismiss" => "modal", type: "button"} Cerrar

app/views/staticpage/my_posts.html.haml
#listing-posts
  .container
    %center 
      .title-section
        LISTADO DE TUS TRABAJOS
      .subtitle-section
        %button.btn.btn-primary.btn-login#registerButton
          - if current_user.permit_post?
            = link_to "Nuevo Post", new_post_path
          - elsif current_user.role != "normal"
            = link_to "Nuevo Post", new_post_path
          - elsif current_user.data_blank?
            = link_to_function 'Nuevo Post', 'alert_perfil()', "data-target" => "#validate_perfil", "data-toggle" => "modal"
          - else
            = link_to_function 'Nuevo Post', 'alert_comment()', "data-target" => "#myModal", "data-toggle" => "modal"
      .line-section{ style: "margin-bottom: 18px;"}
      
    #categories{style: "padding-top: 0px;"}
      .row{ style: "padding-top: 20px;" }
        - if @posts.count == 0
          %center
            %h1{style: "color: #00A2FF; margin-bottom: 600px; margin-top: 168px;"} Aún no has escrito algún Post
        - @posts.each_with_index do |p, index|
          - if index.modulo(3) == 0
            .row{ style: "margin-bottom: 10px;"}
          .col-lg-4.col-md-4.col-sm-4.col-xs-12
            %center 
              .type-img
                - if p.category_id == 1
                  - case Random.rand(1..4)
                    - when 1
                      .type-img-narrativa-1
                    - when 2
                      .type-img-narrativa-2
                    - when 3
                      .type-img-narrativa-3
                    - when 4
                      .type-img-narrativa-4
                - elsif p.category_id == 2
                  - case Random.rand(1..4)
                    - when 1
                      .type-img-poesia-1
                    - when 2
                      .type-img-poesia-2
                    - when 3
                      .type-img-poesia-3
                    - when 4
                      .type-img-poesia-4
                - elsif p.category_id == 3
                  - case Random.rand(1..4)
                    - when 1
                      .type-img-audiovisual-1
                    - when 2
                      .type-img-audiovisual-2
                    - when 3
                      .type-img-audiovisual-3
                    - when 4
                      .type-img-audiovisual-4
                .cover
                %span#item.fa-stack.fa-lg{style:"font-size:50px;"} 
                  %i.fa.fa-circle.fa-stack-2x{style:"color: white;"}
                  %i.fa.fa-eye.fa-stack-1x{style: "color: #00A2FF;"}
                .flat-categories
                  - if p.category_id == 1
                    %i.fa.fa-comment.fa-3x{style: "color:#EFF2FB;"}
                  - elsif p.category_id == 2
                    %i.fa.fa-pencil.fa-3x{style: "color:#EFF2FB;"}
                  - elsif p.category_id == 3
                    %i.fa.fa-youtube-play.fa-3x{style: "color:#EFF2FB;"}
                .flat-dos.arrow-left
                .flat-tres.arrow-right
                = link_to preview_path(p.id), id: "item" do
                  %span.fa-stack.fa-lg{style:"font-size:50px;"} 
                    %i.fa.fa-circle.fa-stack-2x{style:"color: white;"}
                    %i.fa.fa-eye.fa-stack-1x{style: "color: #00A2FF;"}
            %h4 
              = "#{p.title} - "
              %span{ style: "color: #00A2FF;"}
                %strong  
                  = "#{p.category}"

              = link_to "Vista previa", preview_path(p.id), class: "leer-mas pull-right"
//modal de instrucciones para comentarios
#myModal.modal.fade.bs-example-modal-sm{"aria-hidden" => "true", "aria-labelledby" => "mySmallModalLabel", :role => "dialog", :style => "display: none;", :tabindex => "-1"}
  .modal-dialog.modal-sm
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
        %h4#mySmallModalLabel.modal-title 
          %center Instrucción
      .modal-body
        Debes 
        %strong{ style: "color: green; "} COMENTAR 
        al menos 3 posts diferentes para poder publicar y ser parte del concurso.
    / /.modal-content
  / /.modal-dialog

  //modal de instrucciones para comentarios
#validate_perfil.modal.fade.bs-example-modal-sm{"aria-hidden" => "true", "aria-labelledby" => "mySmallModalLabel", :role => "dialog", :style => "display: none;", :tabindex => "-1"}
  .modal-dialog.modal-sm
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
        %h4#mySmallModalLabel.modal-title 
          %center Instrucción
      .modal-body
        Debes 
        %strong{ style: "color: green; "} INGRESAR 
        todos los datos de tu perfil.
        = link_to "Editar perfil".html_safe, edit_user_registration_path, :class=>"btn btn-login", :title=>'Editar Perfil'
    / /.modal-content
  / /.modal-dialog

:javascript
  function alert_comment() {
    $('#myModal').modal(options)
  }

  function alert_perfil() {
    $('#validate_perfil').modal(options)
  }

  if ("#{request.original_url.scan("my_posts").count}" == 1) {
    $('.top-nav .active').removeClass("active")
    $('.top-nav li').eq(5).addClass("active")
  }

app/views/staticpage/preview.html.haml
.show-post
	.container  
		%h3
			= @post.title
		.autor
			%small
				%strong= "#{@post.user.name}, "
				= @post.created_at.strftime("%B %d, %Y")
		.content
			- if @post.category_id == 3 and @post.attachments.count == 0
				.video-container
					%center 
						%iframe{:allowfullscreen => "", :frameborder => "0", :height => "315", :src => "#{@post.video.gsub('watch?v=', 'embed/')}", :width => "560"}
			- elsif @post.category_id == 3 and @post.attachments.count > 0
				- @post.attachments.each do |image|
					.col-sm-12.col-md-12.col-sm-12.col-xs-12#list-images
						= image_tag image.file_url
					%hr
			- else
				%p{align:"justify", style:"color:#777;"}
					= "#{@post.content}".html_safe
			%br/ 

:javascript
	if ("#{request.original_url.scan("my_posts").count}" == 1) {
		$('.top-nav .active').removeClass("active")
		$('.top-nav li').eq(5).addClass("active")
	  }

app/views/staticpage/show.html.haml
= content_for(:title, "#{@post.title}")
.show-post
  .container  
    %h3
      = @post.title
    .autor
      %small
        = link_to "<strong>#{@post.user.name}</strong>, ".html_safe, perfil_path(@post.user.id)
        = @post.created_at.strftime("%B %d, %Y")
    .content
      - if @post.category_id == 3 and @post.attachments.count == 0
        .video-container
          %center 
            %iframe{:allowfullscreen => "", :frameborder => "0", :height => "315", :src => "#{@post.video.gsub('watch?v=', 'embed/')}", :width => "560"}
      - elsif @post.category_id == 3 and @post.attachments.count > 0
        - @post.attachments.each do |image|
          .col-sm-12.col-md-12.col-sm-12.col-xs-12#list-images
            = image_tag image.file_url
          %hr
      - else
        = @post.content.html_safe
    
    .votes.col-sm-12.col-md-12.col-sm-12.col-xs-12{ style: "margin-bottom: 30px;"}
      %center

        = link_to like_post_path(@post.id), method: :put, class: "btn btn-primary" do
          %i.fa.fa-thumbs-up.fa-1x
          %span.badge= @post.upvotes.size
        
        /= link_to dislike_post_path(@post.id), method: :put, class: "btn btn-danger" do
        /%i.fa.fa-thumbs-down.fa-1x
        /%span.badge= @post.downvotes.size

    .col-sm-12.col-md-12.container-social.visible-sm.visible-md.visible-lg
      .col-xs-2.col-sm-3.col-md-3.col-lg-2.links-socials#social-facebook
        .fb-like{"data-action" => "like", "data-href" => "#{request.url}", "data-layout" => "button_count", "data-share" => "false", "data-show-faces" => "true"}
      .col-xs-2.col-sm-3.col-md-3.col-lg-2.links-socials#social-gplus
        .g-plus{"data-action"=>"share", "data-annotation"=>"bubble"}
      .col-xs-2.col-sm-3.col-md-3.col-lg-2.links-socials#social-twitter
        = link_to "Twittear", "https://twitter.com/share", class: "twitter-share-button", "data-lang" => "es", "data-text" => "#tremmel #{@post.title}", "data-url" => "#{request.url}", "data-via" => "tremmelca"
    %ul.ul-xs-socials.visible-xs
      %center
        %li#like
          .fb-like{"data-action" => "like", "data-href" => "#{request.url}", "data-layout" => "button_count", "data-share" => "false", "data-show-faces" => "true"}
        %li#plus
          .g-plus{"data-action"=>"share", "data-annotation"=>"bubble"}
        %li#tw
          = link_to "Twittear", "https://twitter.com/share", class: "twitter-share-button", "data-lang" => "es", "data-text" => "#MiCreacion #{@post.title}", "data-url" => "#{request.url}", "data-via" => "@creador3s"

  

    .container#comment-area{ style: "width:100%;"}
      .col-sm-12.col-md-12{style:"padding:0px;"}
        .col-sm-12.col-md-12{style:"padding:0px;"}
          %hr
          %h3{ style: "color: #1270A6;" } Comentarios
          - if @post.comments.count == 0
            .comment
              No hay comentarios
          - else
            .comments
              - @post.comments.reverse.each do |c|
                .media
                  %a.pull-left{href: "#"}
                    - unless  c.user
                      %img.media-object{alt: "...", src: "http://assets.witendofi.com/assets/default-avatar-2c18690c1ead5b30559911a0d7764ce0.png", style: "width:64px; heigth:64px;"}/
                    - else 
                      = image_tag c.user.avatar_url, id: "avatar-comment"
                  .media-body
                    %small.pull-right= time_ago_in_words(c.created_at)                
                    %h4.media-heading= c.user ? "#{c.user.name} <small><span style='color: #1270A6;'>Participante</span></small>".html_safe : c.name
                    = c.comment
          %hr
          %h3{ style: "color: #1270A6;"} Deja tu comentario

          %div#comentar
            = form_tag "/posts/add_new_comment" do
              = hidden_field_tag :id, @post.id
              = hidden_field_tag :user_id, current_user ? current_user.id : nil
              - unless current_user
                .col-md-12.input-comment
                  Nombre
                  = text_field_tag :name, nil,class: "form-control"
                %br
              .col-md-12.input-comment
                Contenido
                = text_area_tag :comment, nil,class: "form-control"
              %br
              %p
                = submit_tag "Comentar", class: 'button btn btn-primary btn-login'

:javascript
  //twitter share
  !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
  
  //facebook share
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/es_LA/all.js#xfbml=1";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));

  //google+ share
  window.___gcfg = {lang: 'es'};

  (function() {
    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
    po.src = 'https://apis.google.com/js/platform.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
  })();