config/routes.rb
Creators::Application.routes.draw do
  
  resources :admin, only: [:index]
  resources :posts do
    member do
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
  end

  match "/posts/add_new_comment" => "staticpage#add_new_comment", :as => "add_new_comment_to_posts", :via => [:post]
  get '/my_posts', to: 'staticpage#my_posts', as: 'my_posts'
  get '/my_posts/:id/preview', to: 'staticpage#preview', as: 'preview'
  get '/show/:id', to: 'staticpage#show', as: 'show_staticpage'
  get '/user/:id', to: 'admin#user', as: 'show_user'
  get 'admin/:id/publish_unpublish_post', to: 'admin#publish_unpublish_post', as: 'public'
  get 'admin/post/:id/comments',  to: 'admin#posts_comments', as: 'comments'
  delete '/comment/:id', :to => 'admin#destroy', as: 'delete_comments'
  get "/:category" => 'staticpage#home', as: :home_category
  get 'user/perfil/:id',  to: 'staticpage#perfil_usuario', as: 'perfil'
  post "staticpage/enviar_contacto", path: "enviarContacto"

  devise_for :users

  root 'staticpage#home'

end

app/views/admin/index.html.haml
#listing-posts
  .container
    .panel.panel-default
      / Default panel contents
      .panel-heading Listado de Posts
      / Table
      %table.table
        %thead
          %tr
            %th #
            %th Título
            %th Autor
            %th ¿Publicado?
            %th Fecha de publicación
            %th Acciones
        %tbody
          - @posts.reverse.each do |post|
            %tr
              %td= post.id
              %td
                %strong= post.title
              %td
                = link_to post.user.name, show_user_path(post.user_id)
              - if post.public
                %td
                  %span.glyphicon.glyphicon-ok-circle
              - else
                %td
                  %span.glyphicon.glyphicon-remove-circle
              %td= post.created_at.strftime("%B %d, %Y")
              %td
                = link_to 'Supervisar', post
                | #{link_to 'Editar', edit_post_path(post)} | #{link_to 'Comentarios', comments_path(post.id)} | #{post.public == false ? link_to("Publicar", public_path(post.id)) : link_to("Despublicar", public_path(post.id))} | #{link_to 'Eliminar', post, method: :delete, data: { confirm: '¿Estas seguro de querer eliminar?' }}

app/views/admin/posts_comments.html.haml
#listing-posts
  .container
    .panel.panel-default
      / Default panel contents
      .panel-heading= "Listado de comentarios para el Post - #{@post.title}"
      / Table
      %table.table
        %thead
          %tr
            %th #
            %th Nombre
            %th Comentario
            %th Acción
        %tbody
          - @post.comments.reverse.each do |c|
            %tr
              %td= c.id
              %td
                - unless c.name.blank?
                  %strong= c.name
                - else
                  %strong= c.user.name
              %td= c.comment
              %td
                = link_to 'Eliminar', delete_comments_path(c.id),:confirm => '¿Estas seguro de querer eliminar?', :method => :delete 
                

app/views/admin/user.html.haml
#listing-posts
	.container
		%center 
			.title-section
				DATOS DE USUARIO
			.line-section{ style: "margin-bottom: 18px;"}
		.container-resgister2
			%center
				%p  
					%label
						Nombre y Apellido: 
					= @user.name
				%p 
					%label
						Cédula:
					= @user.cedula
				%p 
					%label
						Télefono
					= @user.phone
				%p 
					%label
						Ciudad
					= @user.city
				%p 
					%label
						Fecha de Nacimiento:
					= @user.date_of_birth
				%p 
					%label
						Email:
					= @user.email
				%p 
					%label
						Cantidad de Post comentados:
					= @user.cantidad_de_comentarios
				%p 
					%label
						Cantidad de Posts Escritos:
					= @user.cantidad_de_posts
				%label
				%label
				%label
				%label
				%label