config/routes.rb
Creators::Application.routes.draw do
  
  resources :admin, only: [:index]
  resources :posts do
    member do
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
  end

  match "/posts/add_new_comment" => "staticpage#add_new_comment", :as => "add_new_comment_to_posts", :via => [:post]
  get '/my_posts', to: 'staticpage#my_posts', as: 'my_posts'
  get '/my_posts/:id/preview', to: 'staticpage#preview', as: 'preview'
  get '/show/:id', to: 'staticpage#show', as: 'show_staticpage'
  get '/user/:id', to: 'admin#user', as: 'show_user'
  get 'admin/:id/publish_unpublish_post', to: 'admin#publish_unpublish_post', as: 'public'
  get 'admin/post/:id/comments',  to: 'admin#posts_comments', as: 'comments'
  delete '/comment/:id', :to => 'admin#destroy', as: 'delete_comments'
  get "/:category" => 'staticpage#home', as: :home_category
  get 'user/perfil/:id',  to: 'staticpage#perfil_usuario', as: 'perfil'
  post "staticpage/enviar_contacto", path: "enviarContacto"

  devise_for :users

  root 'staticpage#home'

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :attachments
  accepts_nested_attributes_for :attachments

	before_create :default_values
	before_save :validation_values, :add_city
	acts_as_commentable
  acts_as_votable
  paginates_per 6

  validates_presence_of :title, :user_id, :category_id
  validates :title, uniqueness: true
  validate :validation_audiovisual?, :validation_content?

  #Posts narrativas
  def self.narrativas
    Post.where(category_id: 1)
  end

  #Posts poesias
  def self.poesias
    Post.where(category_id: 2)
  end

  #Posts audiovisuales
  def self.audiovisuales
    Post.where(category_id: 3)
  end

  #search
  def self.search(search)
    if search
      @post = find(:all, :conditions => ['autor iLIKE ? OR title iLIKE ? OR city iLIKE ?', ["%#{search}%"]*3].flatten)
    else
      @post = find(:all)
    end
  end
  #--------------------------------

	def user
		User.find(self.user_id)
	end

  
  def category
    Category.find(self.category_id).name
  end

  def video_conversion
    self.video.gsub('watch?v=', 'embed/')
  end

  #---------------------------------

	private

  def default_values
    self.public = 0
  end

  def add_city
    self.city = User.find(self.user_id).city
  end

  def validation_values
  	unless self.category_id == 3
    	self.video = "N/A"
    else
    	self.content = "N/A"
    end
      self.autor = User.find(self.user_id).name
  end

  def validation_audiovisual?
    if self.category_id == 3 and self.attachments.blank? and self.video.blank?
      errors.add(:audiovisual, "debe al menos subir un video o una imagen")
    end 
  end

  def validation_content?
    if self.category_id != 3 and self.content.blank?
      errors.add(:contenido, "no puede estar en blanco")
    end 
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  layout "admin", only: [:show, :edit]
  load_and_authorize_resource #ability cancan uso para modelo
  skip_load_resource :only => [:create]
  before_filter :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    authorize! :show, @posts if current_user
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
    unless current_user.permit_post? #permitir escribir post solo a users que hayan hecho 3 comentariso en 3 post diferentes
      if current_user.role == "normal" #validar raise si el usuario no es administrador
        raise CanCan::AccessDenied.new("Debes COMENTAR al menos 3 posts diferentes para poder publicar y ser parte del concurso.", :edit, Post)
      end
    end

    if current_user.data_blank? #permitir escribir post solo a users que hayan hecho 3 comentariso en 3 post diferentes
      if current_user.role == "normal" #validar raise si el usuario no es administrador
        raise CanCan::AccessDenied.new("Debes completar tus datos en editar perfil", :edit, Post)
      end
    end
  end

  # GET /posts/1/edit
  def edit
    #autorizar edicion de post al administrador que cumpla con el role
    if @post.category_id != current_user.role.to_i
      raise CanCan::AccessDenied.new("No estas autorizado para editar este post.", :edit, Post)
    end
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to preview_path(@post.id), notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to admin_index_path }
      format.json { head :no_content }
    end
  end

  def upvote
    @post = Post.find(params[:id])
    @post.liked_by current_user
    redirect_to show_staticpage_path(@post.id)
  end

  def downvote
    @post = Post.find(params[:id])
    @post.downvote_from current_user
    redirect_to show_staticpage_path(@post.id)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :video, :public, :category_id, :user_id, :autor, attachments_attributes: [:id, :file])
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.haml
= nested_form_for @post, :html=>{:multipart => true } do |f|
  - if @post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@post.errors.count, "error")} Debe llenar los siguientes campos de forma correcta."
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label "Categoría"
    = f.select :category_id, options_for_select(Category.all.collect {|u| [ u.name, u.id ] }), {}, class: "form-control input-register" 
    = f.hidden_field :user_id, value: current_user.id
  .field
    = f.label "Título"
    = f.text_field :title, class: "form-control input-register"
  .field
    .btn-group#btn-select
      %button.btn.btn-default{:type => "button",  onclick: "input_show('images');"} Imagenes
      %button.btn.btn-default{:type => "button", onclick: "input_show('video');"} Video
    %br
    %br
  .field#content
    = f.label "Contenido"
    = f.text_area :content, class: "ckeditor input-register", style: "height: 300px;"
  .field#video
    = f.label "Vídeo"
    = f.text_field :video, class: "form-control"
  .field#images
    = f.fields_for :attachments do |attachment_form|  
      %p
        = attachment_form.label "Imagen"
        = attachment_form.file_field :file
      = attachment_form.link_to_remove "Remover Imagen"
    = f.link_to_add "Añadir imagen", :attachments
  .field.pull-right
    = f.submit 'Guardar', class: "btn btn-primary btn-login"

:javascript
  category_inputs();
  var config = {
    toolbarGroups: [
      { name: 'basicstyles', groups: [ 'basicstyles', 'cleanup' ] }, 
      //{ name: 'paragraph', groups: [ 'blocks', 'align' ] }
    ],
    align: "justify"
  };

  $('.ckeditor').ckeditor(config,{
    
  });

app/views/posts/edit.html.haml
.container
	%h1 Editar Post

	= render 'form'

	= link_to 'Show', @post
	\|
	= link_to 'Back', admin_index_path

app/views/posts/index.html.haml
#listing-posts
  .container
    %center 
      .title-section
        LISTADO DE TUS TRABAJOS
      .subtitle-section
        %button.btn.btn-primary.btn-login#registerButton
          = link_to "Nuevo Post", new_post_path
      .line-section{ style: "margin-bottom: 18px;"}

    %table
      %tr
        %th Title
        %th Content
        %th Video
        %th Public
        %th Category
        %th User
        %th
        %th
        %th

      - @posts.each do |post|
        %tr
          %td= post.title
          %td= post.content
          %td= post.video
          %td= post.public
          %td= post.category_id
          %td= post.user_id
          %td= link_to 'Show', post
          %td= link_to 'Edit', edit_post_path(post)
          %td= link_to 'Destroy', post, :method => :delete, :data => { :confirm => 'Are you sure?' }

    %br

    = link_to 'New Post', new_post_path

app/views/posts/new.html.haml
#new_post
	.container
		%center 
			.title-section
				NUEVO POST
			.subtitle-section
				La creatividad es un don, pon tu imaginación a volar
			.line-section{ style: "margin-bottom: 18px;"}

		= render 'form'

		= link_to 'Volver', my_posts_path, class: "btn btn-primary btn-login"

app/views/posts/show.html.haml
.show-post
  .container  
    %h3
      = @post.title
    .autor
      %small
        = link_to "<strong>#{@post.user.name}</strong>, ".html_safe, perfil_path(@post.user.id)
        = @post.created_at.strftime("%B %d, %Y")
    .content
      - if @post.category_id == 3 and @post.attachments.count == 0
        .video-container
          %center 
            %iframe{:allowfullscreen => "", :frameborder => "0", :height => "315", :src => "#{@post.video.gsub('watch?v=', 'embed/')}", :width => "560"}
      - elsif @post.category_id == 3 and @post.attachments.count > 0
        - @post.attachments.each do |image|
          .col-sm-12.col-md-12.col-sm-12.col-xs-12#list-images
            = image_tag image.file_url
          %hr
      - else
        %p{align:"justify", style:"color:#777;"}
          = "#{@post.content}".html_safe
    %p
      %b ¿Está publucado?:
      = @post.public ? "Si" : "No"
      %br/
    %p
      %b Categoría:
      = @post.category
    %p 
      %b Cantidad de comentarios:
      = @post.comments.count