config/routes.rb
Creators::Application.routes.draw do
  
  resources :admin, only: [:index]
  resources :posts do
    member do
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
  end

  match "/posts/add_new_comment" => "staticpage#add_new_comment", :as => "add_new_comment_to_posts", :via => [:post]
  get '/my_posts', to: 'staticpage#my_posts', as: 'my_posts'
  get '/my_posts/:id/preview', to: 'staticpage#preview', as: 'preview'
  get '/show/:id', to: 'staticpage#show', as: 'show_staticpage'
  get '/user/:id', to: 'admin#user', as: 'show_user'
  get 'admin/:id/publish_unpublish_post', to: 'admin#publish_unpublish_post', as: 'public'
  get 'admin/post/:id/comments',  to: 'admin#posts_comments', as: 'comments'
  delete '/comment/:id', :to => 'admin#destroy', as: 'delete_comments'
  get "/:category" => 'staticpage#home', as: :home_category
  get 'user/perfil/:id',  to: 'staticpage#perfil_usuario', as: 'perfil'
  post "staticpage/enviar_contacto", path: "enviarContacto"

  devise_for :users

  root 'staticpage#home'

end

app/views/layouts/admin.html.haml
%html
  %head
    %title Administración - Creators
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = stylesheet_link_tag    "home", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    %link{href: "http://fonts.googleapis.com/css?family=Raleway:400,900", rel: "stylesheet", type: "text/css"}/
    = csrf_meta_tags
  %body
    .loginbar.hidden-xs
      .container
        .row
          .col-md-6.col-sm-4.col-lg-7
            = link_to "Listado de posts", admin_index_path
          - unless current_user 
            .col-md-6.col-sm-8.col-lg-5
              = form_for(:user, :url => user_session_path) do |f|
                = f.text_field :email, class: 'input-login', :placeholder=>"Email"
                = f.password_field :password, class: 'input-login', :placeholder=>"Contraseña"
                = f.submit 'Entrar', class: 'button btn btn-primary btn-login'
          - else
            .col-md-6.col-sm-8.col-lg-5
              .pull-right{style:"margin-top:3px;"}            
                %b{style:"margin-right:5px;"}   
                  %i.fa.fa-user       
                  = current_user.name
                = link_to "Salir", destroy_user_session_path, :method => :delete, :class=>"btn btn-login"
      / /.navbar-collapse
    = yield
    %br

app/views/layouts/application.html.haml
!!!
%html
	= render template: "layouts/head"
	%body
		= render template: "layouts/navbar"
		= yield
		- if params[:action] != "my_posts" or params[:action] != "show"
			.scroll-up
				= link_to_function "<i class= 'fa fa-caret-square-o-up fa-4x'></i>".html_safe, "#home"
				
	%footer
		%center
			Todos los Derechos Reservados. Desarrollado por 
			%span 
				%b 
					%a{href:'http://www.tremmelca.com/', target:'_blank'}
						TREMMEL
					
					

:javascript
	$(".scroll-up a").click(function() {
		$("body").animate({ scrollTop: 0 }, "slow");
		return false;
	});

app/views/layouts/contactanos.html.haml
#contactanos
	- if flash[:alert]
		.container{ style: "background-color=#00A2FF:"}
			%center	
				.alert.alert-danger#notice 
					%button{ type:"button", class: "close", "data-dismiss"=>"alert", "aria-hidden"=>"true"}
						%i.fa.fa-times
					%center
						= "#{flash[:alert]}"
	.container
		%center 
			.title-section
				%b
					¡CONTÁCTANOS!
			.subtitle-section
				III Encuentro Literario de Jóvenes Creadores
			.line-contactanos
		
			.contactos-box-min
				.row
					= form_tag({controller: "staticpage", action: "enviar_contacto"}, {class: "contact_form"}) do
						.row
							.col-md-12  
								= text_field_tag :name, "", :class=>'contactos-input', :type => "text", :placeholder=>'Nombre'
							.col-md-12
								= text_field_tag :email, "", :class=>'contactos-input', :type => "text", :placeholder=>'Email'
						.row
							.col-md-12
								= text_area_tag :comment, "", :class=>'contactos-textarea' , :placeholder=>'Mensaje'
						.row
							.col-md-12
							/= show_simple_captcha
						.row
							.col-md-12
								= button_tag(type: 'submit', class: "btn btn-contactos", style:"width:100%") do
									%i.fa.fa-envelope.fa-2x{style: "color:white;"}
			%br/ 
			%br/ 
			.row
				.col-md-3.col-sm-3.col-xs-3							
					%a{:href => "https://www.facebook.com/creador3s?fref=ts", target: "_blank", style:"color:#fff;" }
						%i.fa.fa-facebook-square.fa-5x
				.col-md-3.col-sm-3.col-xs-3					
					%a{:href => "https://twitter.com/creador3s", target: "_blank", style:"color:#fff;" }
						%i.fa.fa-twitter-square.fa-5x 	
				.col-md-3.col-sm-3.col-xs-3						
					%a{:href => "", target: "_blank", style:"color:#fff;" }
						%i.fa.fa-google-plus-square.fa-5x
				.col-md-3.col-sm-3.col-xs-3						
					%a{:href => "", target: "_blank", style:"color:#fff;" }
						%i.fa.fa-youtube-square.fa-5x 
			%br/	
			%br/
			%center
				%i.fa.fa-envelope.fa-2x
				info@jovenescreadores.org
				%br 
				%br
				

app/views/layouts/evento.html.haml
#evento
	.container
		%center 
			.title-section
				%b
					EVENTO
			.subtitle-section
				III Encuentro Literario de Jóvenes Creadores
			.line-section
		.row
			.col-lg-4.col-md-4
				%p{align:"justify"}
					El 
					%b
						ENCUENTRO LITERARIO DE JÓVENES CREADORES 
					tiene como fin, Promover sin fines de lucro, el arte y la cultura, la intención principal de este encuentro es dar a conocer escritores inéditos, así como promocionar sus obras y propiciar el compartir de textos y opiniones de índole literaria creando un espacio de exposición y discusión de literatura contemporánea no publicada. La dinámica del evento implica no sólo la simple exposición de sus obras por parte de cada participante sino también la convicción y el compromiso de leer las obras de los demás escritores involucrados. El encuentro se llevará a cabo durante tres días consecutivos en los que se compartirá ensayo, poesía audiovisuales y narrativa.
			.col-lg-4.col-md-4
				%p{align:"justify"}
					%center
						= image_tag "logo-color.png", :width => "300px"
			.col-lg-4.col-md-4
				%p{align:"justify"}
					%b
						CRITERIOS GENERALES PARA PARTICIPACION EN EL EVENTO:
					%b
						1ero: 
					Sólo se aceptarán textos y trabajos audiovisuales inéditos. Sí podrán participar trabajos publicados en blogs personales o redes sociales.
					%b
						2do:
					El creador podrá participar en una categoría o en varias, simultáneamente.
					%b
						3ro: 
					Sólo se aceptarán textos y trabajos audiovisuales inéditos. Sí podrán participar trabajos publicados en blogs personales o redes sociales. 
					%b
						4to: 
					Cada Participante debe comentar al menos 3 trabajos subidos a este portal, luego estará habilitado automáticamente para poder subir el propio, desde su cuenta de usuario se puede subir el material en las diferentes categorías.	
		.row
			.col-lg-4.col-md-4.col-sm-12.col-xs-12
				%p{align:"justify"}
					%i.fa.fa-pencil.fa-2x
					%b POESIA
					No habrá limitaciones temáticas, y se aceptará prosa poética o lírica. La extensión máxima será de 10 cuartillas en tipografía Times New Roman o Arial, tamaño 12 e interlineado 1,5. Los poemas enviados no deberán estar publicados por editoriales.
			.col-lg-4.col-md-4.col-sm-12.col-xs-12				
				%p{align:"justify"}
					%i.fa.fa-comment.fa-2x
					%b NARRATIVA
					Se aceptará microcuentos y cuentos, que no hayan sido publicados por editoriales y que tengan una extensión máxima de 10 cuartillas en tipografía Times New Roman o Arial, tamaño 12 e interlineado 1,5.
			.col-lg-4.col-md-4.col-sm-12.col-xs-12
				%p{align:"justify"}
					%i.fa.fa-youtube-play.fa-2x					
					%b AUDIOVISUALES
					Publica tu video inédito de hasta 10 minutos en YouTube y coloca el link en tu publicacion, incluir descripciones técnicas de la obra y biofilmografía de los responsables. Tambien puedes subir 5 de tus dibujos digitalizados o 5 de tus mejores fotografias.			
		.row
			.col-lg-12.col-md-12	
				%p{align:"justify"}
					%b
						Nota Importante:
					en el caso de que necesites una carta de invitación al
					%b
						“Encuentro Literario de Jóvenes Creadores”
					dirigida a la casa de estudios donde perteneces, deberás informarlo en el mail y enviar los siguientes datos -Nombre Completo – Cédula de Identidad – Nombre de Casa de Estudios.
		%br/ 
		.row
			%center
				.col-lg-6.col.md-6
					%a.btn.btn-primary.btn-login#registerButton{:href => "", :style=>'width:300px'}
						%i.fa.fa-calendar
						Ver Cronograma
				%br.hidden-lg
				.col-lg-6.col.md-6
					%a.btn.btn-primary.btn-login#registerButton{:href => "",  :style=>'width:300px'}
						%i.fa.fa-bookmark
						Reglas del Encuentro
		

app/views/layouts/head.html.haml
%head
	%meta{:content => "width=device-width, initial-scale=1, maximum-scale=1", :name => "viewport"}
	= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
	= stylesheet_link_tag    "home", media: "all", "data-turbolinks-track" => true
	= javascript_include_tag "application", "data-turbolinks-track" => true
	= javascript_include_tag :defaults, "nested_form"
	= favicon_link_tag 'favicon.png' 
	%title= content_for?(:title) ? yield(:title) : "Jovenes Creadores"
	%link{href: "http://fonts.googleapis.com/css?family=Raleway:400,900", rel: "stylesheet", type: "text/css"}/
	%link{href:'http://fonts.googleapis.com/css?family=Open+Sans', rel:'stylesheet', type:'text/css'}
	= csrf_meta_tags
	:javascript
		(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

		ga('create', 'UA-50795914-1', 'jovenescreadores.org');
		ga('send', 'pageview');

app/views/layouts/navbar.html.haml
.loginbar
	.container
		.row
			.col-md-6.col-sm-4.col-lg-7
				.header-navbar.hidden-xs.hidden-sm
					= image_tag "logo-color.png", :width => "200px"
			- unless current_user 
				.col-md-6.col-sm-8.col-lg-5.hidden-xs
					= form_for(:user, :url => user_session_path) do |f|
						= f.text_field :email, class: 'input-login', :placeholder=>"Email"
						= f.password_field :password, class: 'input-login', :placeholder=>"Contraseña"
						= f.submit 'Entrar', class: 'button btn btn-primary btn-login'
				.col-md-6.col-sm-8.col-lg-5.visible-xs
					= link_to "¡Registrate!", new_user_registration_path, class: 'button btn btn-primary btn-login pull-right'
					= link_to "Login", new_user_session_path, class: 'button btn btn-primary btn-login pull-right', style: "margin-right: 10px;"
			- else
				.col-md-6.col-sm-8.col-lg-5
					.pull-right{style:"margin-top:3px;"}			
						= link_to "<i class='fa fa-user'> #{current_user.name}</i>".html_safe, perfil_path(current_user.id), :class=>"btn btn-login", :title=>'Ver Perfil', id: "user-perfil"
						= link_to "<i class='fa fa-cog'></i>".html_safe, edit_user_registration_path, :class=>"btn btn-login", :title=>'Editar Perfil'
						= link_to "<i class='fa fa-sign-out'></i>".html_safe, destroy_user_session_path, :method => :delete, :class=>"btn btn-login", :title=>'Cerrar Sesión'


%nav.navbar.navbar-default{role: "navigation"}
	.navbar-header
		%button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
			%span.sr-only Toggle navigation
			%span.icon-bar
			%span.icon-bar
			%span.icon-bar
		%a.navbar-brand
		%div.visible-xs.navbar-brand
	#bs-example-navbar-collapse-1.collapse.navbar-collapse
		%ul.nav.navbar-nav.navbar-right.top-nav
			%li{ class: "#{'active' if params[:action] == 'option'}"}
				= link_to "<center><div class='icon icon-home hidden-xs'></div> <span>Inicio</span></center>".html_safe, root_path(anchor: "home")
			%li{ class: "#{'active' if params[:action] == 'option'}"}
				= link_to  "<center><div class='icon icon-users hidden-xs'></div> <span>Nosotros</span></center>".html_safe,root_path(anchor: "nosotros")
			%li{ class: "#{'active' if params[:action] == 'index'}"}
				= link_to  "<center><div class='icon icon-event hidden-xs'></div> <span class>Evento</span></center>".html_safe,root_path(anchor: "evento")
			%li{ class: "#{'active' if params[:action] == 'show'}"}
				= link_to  "<center><div class='icon icon-categorias hidden-xs'></div> <span>Categorías</span></center>".html_safe, root_path(anchor: "categories") 
			%li{ class: "#{'active' if params[:action] == 'option'}"}
				= link_to  "<center><div class='icon icon-contact hidden-xs'></div> <span>Contáctanos</span></center>".html_safe, root_path(anchor: "contactanos")
			%li 
				- if current_user 
					= link_to  "<center><div class='icon icon-event hidden-xs'></div> <span>Mis Posts</span></center>".html_safe, my_posts_path, class: "external"
			
						

app/views/layouts/nosotros.html.haml
#nosotros
	.container
		%center 
			.title-section
				%b
					NOSOTROS
			.subtitle-section
				¿Quiénes Organizan el III Encuentro Literario de Jóvenes Creadores?
			.line-section
		.row
			.col-lg-4.col-md-4
				%p{align:"justify", style:"font-family: 'Open Sans', 'sans-serif';"}
					La fundación por el Movimiento Artístico Cultural que Hace Efecto y Tumba Estrellas (MACHETE), nace con la misión inequívoca y constante de promover e impulsar, sin fines de lucro, el arte y la cultura en todas sus presentaciones, especialmente las tendencias del tipo alternativas, las cuales son poco consideradas y apoyadas por los medios oficiales; esto se realiza a través de la planificación, organización, producción y difusión de eventos artísticos y culturales de alto nivel, la publicación de material impreso y cualquier otro medio del que la fundación disponga y considere pertinente para el cumplimiento de las metas.
			.col-lg-4.col-md-4
				%p{align:"justify"}
					%center
						= image_tag "machete-logo.png", :class=>'logo-nosotros img-responsive'
			.col-lg-4.col-md-4
				%p{align:"justify", style:"font-family: 'Open Sans', 'sans-serif';"}
					MACHETE se mueve con la ambiciosa visión de ser pioneros en la producción, promoción y difusión de obras y eventos de índole artística y cultural, con un alcance de proporciones nacionales e internacionales, la idea fundamental es que estos eventos propicien el intercambio de talentos regionales y nacionales así como impulsar la proyección de las nuevas voces de la creación artística en todas las categorías. Es por nuestro objetivo principal que traemos a ustedes la III edición del encuentro de jóvenes talentosos, donde encontrará un intercambio literario de altos niveles, listos para la proyección nacional e internacional.
		
		

app/views/layouts/patrocinantes.html.haml
#patrocinantes
	.container
		%center 
			.title-section
				%b
					PATROCINANTES
			.subtitle-section
				Ellos Hacen Posible el III Encuentro Literario de Jóvenes Creadores
			.line-patrocinante
	#myCarousel2.carousel.slide			
		.carousel-inner
			.active.item.item-commercial											
				.col-lg-3.col-md-3.col-sm-6.col-xs-12
					%center 
						.content-img-client
						/	=image_tag "cliente6.png", width: "100%;"
				.col-lg-3.col-md-3.col-sm-6.col-xs-12
					%center 
						.content-img-client
						/	=image_tag "cliente6.png", width: "100%;"
				.col-lg-3.col-md-3.col-sm-6.col-xs-12
					%center 
						.content-img-client
						/	=image_tag "cliente6.png", width: "100%;"
				.col-lg-3.col-md-3.col-sm-6.col-xs-12
					%center 
						.content-img-client
						/	=image_tag "cliente6.png", width: "100%;"
			.item.item-commercial	
				.col-lg-3.col-md-3.col-sm-6.col-xs-12
					%center 
						.content-img-client
						/	=image_tag "cliente6.png", width: "100%;"
				.col-lg-3.col-md-3.col-sm-6.col-xs-12
					%center 
						.content-img-client
						/	=image_tag "cliente6.png", width: "100%;"
				.col-lg-3.col-md-3.col-sm-6.col-xs-12
					%center 
						.content-img-client
						/	=image_tag "cliente6.png", width: "100%;"
				.col-lg-3.col-md-3.col-sm-6.col-xs-12
					%center 
						.content-img-client
						/	=image_tag "cliente6.png", width: "100%;"
			.item.item-commercial			
				.col-lg-4.col-md-4.col-sm-6.col-xs-12
					%center 	
						.content-img-client
						/	=image_tag "cliente6.png", width: "100%;"
				.col-lg-4.col-md-4.col-sm-6.col-xs-12
					%center 
						.content-img-client
						/	=image_tag "cliente6.png", width: "100%;"
				.col-lg-4.col-md-4.col-sm-6.col-xs-12
					%center 
						.content-img-client
						/	=image_tag "cliente6.png", width: "100%;"

		%a.carousel-control.carousel-control-commercial.left{"data-slide" => "prev", href: "#myCarousel2", style:"background:none;" } 
			%span.glyphicon.glyphicon-chevron-left.row-commercial{ style: "left: 40px;" }
		%a.carousel-control.carousel-control-commercial.right{"data-slide" => "next", href: "#myCarousel2", style:"background:none" } 
			%span.glyphicon.glyphicon-chevron-right.row-commercial{ style: "right: 40px;" }
.container{ style: "width:100%; padding: 0px; margin-top:0px;"}
	#map_canvas